kind: ConfigMap
shift:
 - name: shift
   time: "* * * * *"
   command: "node server.js --processtype=SHIFT-DISABLED"
   env: dev
 - name: shift-detail
   time: "* * * * *"
   command: "node server.js --processtype=SHIFT-DETAIL-DISABLED"
   env: dev

 - name: shift
   time: "* * * * *"
   command: "node server.js --processtype=SHIFT"
   env: prod
 - name: shift-detail
   time: "* * * * *"
   command: "node server.js --processtype=SHIFT-DETAIL"
   env: prod
