kind: ConfigMap
shift:
 - name: shift
   time: "* * * * *"
   command: "node server.js --processtype=SHIFT"
   env: dev
 - name: shift-detail
   time: "* * * * *"
   command: "echo 'node server.js --processtype=SHIFT-DETAIL';env; curl -vk https://checkmydiary-dev.ukwest.cloudapp.azure.com/api/health"
   env: dev

 - name: shift
   time: "* * * * *"
   command: "node server.js --processtype=SHIFT"
   env: prod
 - name: shift-detail
   time: "* * * * *"
   command: "node server.js --processtype=SHIFT-DETAIL"
   env: prod
