kind: ConfigMap
shift:
 - name: shift
   time: "5 * * * *"
   command: "node server.js --processtype=SHIFT"
   env: dev
 - name: shift-detail
   time: "1 * * * *"
   command: "echo 'node server.js --processtype=SHIFT-DETAIL'"
   env: dev

 - name: shift
   time: "5 * * * *"
   command: "node server.js --processtype=SHIFT"
   env: prod
 - name: shift-detail
   time: "1 * * * *"
   command: "node server.js --processtype=SHIFT-DETAIL"
   env: prod
