apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
      - name: {{ .Values.applicationName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.nodePort }}
        env:
          - name: "PORT"
            value: "{{ .Values.nodePort }}"
          - name: "API_CLIENT_ID"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: api_client_id
          - name: "API_CLIENT_SECRET"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: api_client_secret
          - name: "API_AUTH_ENDPOINT_URL"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: api_auth_endpoint_url
          - name: "TWO_FACT_AUTH_ON"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: two_fact_auth_on
          - name: "REJECT_UNAUTHORIZED"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: reject_unauthorized
          - name: "NOTIFY_CLIENT_KEY"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: notify_client_key
          - name: "NOTIFY_SMS_TEMPLATE"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: notify_sms_template
          - name: "NOTIFY_EMAIL_TEMPLATE"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: notify_email_template
          - name: "GOOGLE_ANALYTICS_ID"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: google_analytics_id
          - name: "WEB_SESSION_TIMEOUT_IN_MINUTES"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: web_session_timeout_in_minutes
          - name: "HMPPS_COOKIE_NAME"
            value: {{ .Values.applicationName }}
          - name: "HMPPS_COOKIE_DOMAIN"
            value: {{ .Values.deploy.host }}
          - name: "NOTIFY_HEALTH_CHECK_URL"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: notify_health_check_url
          - name: "DATABASE_HOST"
            valueFrom:
              secretKeyRef:
                name: check-my-diary-rds-{{ .Values.appEnvironment }}-env
                key: rds_instance_address
          - name: "DATABASE_NAME"
            valueFrom:
              secretKeyRef:
                name: check-my-diary-rds-{{ .Values.appEnvironment }}-env
                key: database_name
          - name: "DATABASE_USER"
            valueFrom:
              secretKeyRef:
                name: check-my-diary-rds-{{ .Values.appEnvironment }}-env
                key: database_username
          - name: "DATABASE_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: check-my-diary-rds-{{ .Values.appEnvironment }}-env
                key: database_password
          - name: "QUANTUM_ADDRESS"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-env
                key: quantum_address
