apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.applicationName }}-ingress
spec:
  tls:                                                                      
  - hosts:
    - {{ .Values.deploy.host }}
  rules:
  - host: {{ .Values.deploy.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.applicationName }}
          servicePort: 3000
