apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    app: {{ .Values.applicationName }}

