apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-my-diary-notification-12hourly
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: notification-container
            image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/check-my-diary/check-my-diary-notification-service-dev:{{ .Values.image.tag }}
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster; exit $(shuf -i 0-1 -n 1)
          restartPolicy: OnFailure