apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-my-diary-notification-12hourly
spec:
  schedule: "0 3,15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: notification-container
            image: 926803513772.dkr.ecr.eu-west-2.amazonaws.com/check-my-diary/check-my-diary-notification-service-dev:{{ .Values.image.tag }}
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
          successfulJobsHistoryLimit: 5
          failedJobsHistoryLimit: 5