{{- $root := . -}}
{{- range .Values.shift }} 
{{- if eq $root.Values.appEnvironment .env }}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-my-diary-notification-{{ .name }}
spec:
  schedule: "{{ .time }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers: 
          - name: notification-container
            image: 926803513772.dkr.ecr.eu-west-2.amazonaws.com/check-my-diary/check-my-diary-notification-service-dev:{{ $root.Values.image.tag }}
            args:
            - /bin/sh
            - -c
            - {{ .command }}
            successfulJobsHistoryLimit: 5
            failedJobsHistoryLimit: 5
            ports:
            - containerPort: {{ $root.Values.nodePort }}
            env:
              - name: "NOTIFICATIONS_API_ENDPOINT_URL"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: notifications_api_endpoint_url
              - name: "NOTIFY_CLIENT_KEY"
                valueFrom:
                  secretKeyRef:
                    name: {{ $root.Values.applicationName }}-env
                    key: notify_client_key
              - name: "NOTIFY_SMS_TEMPLATE"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: notify_sms_template
              - name: "NOTIFY_EMAIL_TEMPLATE"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: notify_email_template
              - name: "DATABASE_HOST"
                valueFrom:
                  secretKeyRef:
                    name: check-my-diary-rds-{{ $root.Values.appEnvironment }}
                    key: rds_instance_address
              - name: "DATABASE_NAME"
                valueFrom:
                  secretKeyRef:
                    name: check-my-diary-rds-{{ $root.Values.appEnvironment }}
                    key: database_name
              - name: "DATABASE_USER"
                valueFrom:
                  secretKeyRef:
                    name: check-my-diary-rds-{{ $root.Values.appEnvironment }}
                    key: database_username
              - name: "DATABASE_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    name: check-my-diary-rds-{{ $root.Values.appEnvironment }}
                    key: database_password
              - name: "BUSINESS_UNIT"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: business_unit
              - name: "INTERVAL"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: interval
              - name: "INTERVAL_TYPE"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: interval_type
              - name: "RUN_AS_JOB"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: run_as_job
              - name: "RUN_EVERY"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: run_every
              - name: "LOG_FILE_LOCATION"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: log_file_location
              - name: "LOG_LEVEL"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: log_level
              - name: "LOG_PERIOD"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: log_period
              - name: "LOG_NUMBER_OF_FILES_TO_KEEP"
                valueFrom:
                  configMapKeyRef:
                    name: {{ $root.Values.applicationName }}-vars
                    key: log_number_of_files_to_keep
          restartPolicy: OnFailure
{{- end }}{{- end }}