apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
      - name: {{ .Values.applicationName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        env:
          - name: "DATABASE_HOST"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-rds-{{ .Values.appEnvironment }}
                key: rds_instance_address
          - name: "DATABASE_NAME"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-rds-{{ .Values.appEnvironment }}
                key: database_name
          - name: "DATABASE_USER"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-rds-{{ .Values.appEnvironment }}
                key: database_username
          - name: "DATABASE_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.applicationName }}-rds-{{ .Values.appEnvironment }}
                key: database_password
