apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  API_CLIENT_ID: {{ .Values.secrets.API_CLIENT_ID | b64enc | quote }}
  API_CLIENT_SECRET: {{ .Values.secrets.API_CLIENT_SECRET | b64enc | quote }}
  API_AUTH_ENDPOINT_URL: {{ .Values.secrets.API_AUTH_ENDPOINT_URL | b64enc | quote }}
  NOTIFY_CLIENT_KEY: {{ .Values.secrets.NOTIFY_CLIENT_KEY | b64enc | quote }}
  GOOGLE_ANALYTICS_ID: {{ .Values.secrets.GOOGLE_ANALYTICS_ID | b64enc | quote }}
